<?php

declare(strict_types=1);

namespace Tests;

use PHPUnit\Framework\Attributes\DataProvider;
use Sunaoka\Damm\Damm;
use Sunaoka\Damm\OrderInterface;

class DammTest extends TestCase
{
    public function test_order_default(): void
    {
        $damm = new Damm('0123456789');

        self::assertSame('4', $damm->calculate('572'));

        self::assertTrue($damm->validate('5724'));
        self::assertFalse($damm->validate('5727'));
        self::assertTrue($damm->validate('112946'));
        self::assertFalse($damm->validate('112949'));
    }

    public function test_order10(): void
    {
        $damm = new Damm('0123456789', new \Sunaoka\Damm\Order\Order10());

        self::assertSame('4', $damm->calculate('572'));

        self::assertTrue($damm->validate('5724'));
        self::assertFalse($damm->validate('5727'));
        self::assertTrue($damm->validate('112946'));
        self::assertFalse($damm->validate('112949'));
    }

    public function test_order36(): void
    {
        $damm = new Damm('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', new \Sunaoka\Damm\Order\Order36());

        self::assertSame('0', $damm->calculate('572'));

        self::assertTrue($damm->validate('5720'));
        self::assertFalse($damm->validate('5727'));
        self::assertTrue($damm->validate('11294W'));
        self::assertFalse($damm->validate('112949'));
    }

    public function test_invalid_characters(): void
    {
        $this->expectException(\InvalidArgumentException::class);

        $damm = new Damm('0123456789', new \Sunaoka\Damm\Order\Order10());

        $damm->calculate('abc');
    }

    /**
     * @dataProvider dataProvider
     *
     * @param class-string<OrderInterface> $class
     */
    #[DataProvider('dataProvider')]
    public function test_orders(string $class, string $characters, string $string, string $expected): void
    {
        $damm = new Damm($characters, new $class);

        self::assertSame($expected, $damm->calculate($string));
        self::assertTrue($damm->validate($string . $expected));
    }

    /**
     * @return array{class-string, string, string}[]
     */
    public static function dataProvider(): array
    {
        return [
            [
                \Sunaoka\Damm\Order\Order3::class,
                '012',
                '102',
                '0',
            ],
            [
                \Sunaoka\Damm\Order\Order4::class,
                '0123',
                '3201',
                '1',
            ],
            [
                \Sunaoka\Damm\Order\Order5::class,
                '01234',
                '31402',
                '3',
            ],
            [
                \Sunaoka\Damm\Order\Order7::class,
                '0123456',
                '5601432',
                '1',
            ],
            [
                \Sunaoka\Damm\Order\Order8::class,
                '01234567',
                '02713546',
                '7',
            ],
            [
                \Sunaoka\Damm\Order\Order9::class,
                '012345678',
                '706215384',
                '6',
            ],
            [
                \Sunaoka\Damm\Order\Order10::class,
                '0123456789',
                '1698274035',
                '8',
            ],
            [
                \Sunaoka\Damm\Order\Order11::class,
                '0123456789A',
                '03981456A27',
                '9',
            ],
            [
                \Sunaoka\Damm\Order\Order12::class,
                '0123456789AB',
                '6907B534A821',
                '9',
            ],
            [
                \Sunaoka\Damm\Order\Order13::class,
                '0123456789ABC',
                '913A7B864C250',
                '1',
            ],
            [
                \Sunaoka\Damm\Order\Order14::class,
                '0123456789ABCD',
                '2568DB94307A1C',
                '1',
            ],
            [
                \Sunaoka\Damm\Order\Order15::class,
                '0123456789ABCDE',
                'B3C84571E96D2A0',
                '7',
            ],
            [
                \Sunaoka\Damm\Order\Order16::class,
                '0123456789ABCDEF',
                '6249AF108E7DB35C',
                '8',
            ],
            [
                \Sunaoka\Damm\Order\Order17::class,
                '0123456789ABCDEFG',
                '2F64AE8DG739BC10',
                '0',
            ],
            [
                \Sunaoka\Damm\Order\Order18::class,
                '0123456789ABCDEFGH',
                'C179B5EDH32G0F64',
                'B',
            ],
            [
                \Sunaoka\Damm\Order\Order19::class,
                '0123456789ABCDEFGHI',
                'CHBG9E475I31028D',
                'H',
            ],
            [
                \Sunaoka\Damm\Order\Order20::class,
                '0123456789ABCDEFGHIJ',
                'G91HC3DEBIF0A752',
                '4',
            ],
            [
                \Sunaoka\Damm\Order\Order21::class,
                '0123456789ABCDEFGHIJK',
                'DKAJ96B7CI8120G4',
                'F',
            ],
            [
                \Sunaoka\Damm\Order\Order22::class,
                '0123456789ABCDEFGHIJKL',
                'I04A28BE651FDHJ7',
                '7',
            ],
            [
                \Sunaoka\Damm\Order\Order23::class,
                '0123456789ABCDEFGHIJKLM',
                '1HFD9JL8IEK47AB2',
                '8',
            ],
            [
                \Sunaoka\Damm\Order\Order24::class,
                '0123456789ABCDEFGHIJKLMN',
                'E290ID1L5K8CBNHM',
                'J',
            ],
            [
                \Sunaoka\Damm\Order\Order25::class,
                '0123456789ABCDEFGHIJKLMNO',
                '8GFJL5C21N670KOB',
                'G',
            ],
            [
                \Sunaoka\Damm\Order\Order26::class,
                '0123456789ABCDEFGHIJKLMNOP',
                'CAKE3I1HB7D9O6J5',
                'D',
            ],
            [
                \Sunaoka\Damm\Order\Order27::class,
                '0123456789ABCDEFGHIJKLMNOPQ',
                'QINAG3OLKC19MD6H',
                'J',
            ],
            [
                \Sunaoka\Damm\Order\Order28::class,
                '0123456789ABCDEFGHIJKLMNOPQR',
                '58M3GEN74JO0DA6B',
                '8',
            ],
            [
                \Sunaoka\Damm\Order\Order29::class,
                '0123456789ABCDEFGHIJKLMNOPQRS',
                '5LRIQ0AD4KM9H71B',
                'G',
            ],
            [
                \Sunaoka\Damm\Order\Order30::class,
                '0123456789ABCDEFGHIJKLMNOPQRST',
                'O36T0AKJSGDIME87',
                'R',
            ],
            [
                \Sunaoka\Damm\Order\Order31::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTU',
                '4L5EDMQ6TU8A0C2J',
                'G',
            ],
            [
                \Sunaoka\Damm\Order\Order32::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUV',
                '8L26DVJQ0NRUB1KC',
                'D',
            ],
            [
                \Sunaoka\Damm\Order\Order33::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVW',
                'JQ19F2DPL703K65U',
                'E',
            ],
            [
                \Sunaoka\Damm\Order\Order34::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWX',
                'RTB5PC0OGM4WHQVK',
                '1',
            ],
            [
                \Sunaoka\Damm\Order\Order35::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXY',
                'XSBQRLA79MHY0IFE',
                'D',
            ],
            [
                \Sunaoka\Damm\Order\Order36::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ',
                'XEIYBMFVTO1QN3AG',
                'Y',
            ],
            [
                \Sunaoka\Damm\Order\Order37::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZa',
                'L61KYJ4C9G0DQURI',
                'C',
            ],
            [
                \Sunaoka\Damm\Order\Order38::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZab',
                'aKBb1IFJ7906SXYC',
                'S',
            ],
            [
                \Sunaoka\Damm\Order\Order39::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabc',
                'AU4CE83YFR75Z6LD',
                'Q',
            ],
            [
                \Sunaoka\Damm\Order\Order40::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcd',
                'F9ObJNc1U7KBCP5H',
                'H',
            ],
            [
                \Sunaoka\Damm\Order\Order41::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcde',
                'FU0417TeMRHPdaXA',
                'N',
            ],
            [
                \Sunaoka\Damm\Order\Order42::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdef',
                'JKbVFIe5dUXGEH97',
                'c',
            ],
            [
                \Sunaoka\Damm\Order\Order43::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefg',
                '8HOL3IENUQ72ACSG',
                'B',
            ],
            [
                \Sunaoka\Damm\Order\Order44::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefgh',
                'JCGPT5E9FDHXSb6W',
                'T',
            ],
            [
                \Sunaoka\Damm\Order\Order45::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghi',
                'FLJ1Eh8SQgNG3Y25',
                'Z',
            ],
            [
                \Sunaoka\Damm\Order\Order46::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghij',
                'icZPU0REAJ6LWKS3',
                'E',
            ],
            [
                \Sunaoka\Damm\Order\Order47::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijk',
                'XWACHbMiF5YhVPGQ',
                'k',
            ],
            [
                \Sunaoka\Damm\Order\Order48::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijkl',
                'B9Ti6FP2LH8MdCAX',
                'N',
            ],
            [
                \Sunaoka\Damm\Order\Order49::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklm',
                'feX9LgQHmbd40WAl',
                'A',
            ],
            [
                \Sunaoka\Damm\Order\Order50::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmn',
                'MkiIK4LNnl10B682',
                'R',
            ],
            [
                \Sunaoka\Damm\Order\Order51::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmno',
                'RkWniQFlAa3o78XG',
                '5',
            ],
            [
                \Sunaoka\Damm\Order\Order52::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop',
                '2AQmVN3ZYn1RHcWj',
                'P',
            ],
            [
                \Sunaoka\Damm\Order\Order53::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopq',
                'I4gRcfo6PeMWHTKp',
                'p',
            ],
            [
                \Sunaoka\Damm\Order\Order54::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqr',
                'nrHAhLoCE0OZBdeR',
                '0',
            ],
            [
                \Sunaoka\Damm\Order\Order55::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrs',
                'EOcRXSg2QrskdWhq',
                'U',
            ],
            [
                \Sunaoka\Damm\Order\Order56::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrst',
                '42CNVpFbBWT79cGq',
                '4',
            ],
            [
                \Sunaoka\Damm\Order\Order57::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstu',
                'DsjlSMuIkEGJ5cKN',
                '6',
            ],
            [
                \Sunaoka\Damm\Order\Order58::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuv',
                'nSBF6ei9N5KPhVga',
                '2',
            ],
            [
                \Sunaoka\Damm\Order\Order59::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvw',
                'UecwnZPk6jYH8oQS',
                'i',
            ],
            [
                \Sunaoka\Damm\Order\Order60::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwx',
                '1iPNmQsJFUxVXfg0',
                'x',
            ],
            [
                \Sunaoka\Damm\Order\Order61::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxy',
                'bNciXG69Y0fOmWx8',
                'h',
            ],
            [
                \Sunaoka\Damm\Order\Order62::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz',
                'I9K6jbDgSoAXLrfc',
                'u',
            ],
            [
                \Sunaoka\Damm\Order\Order63::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz+',
                'ldWTn1zJsybGq7AF',
                'X',
            ],
            [
                \Sunaoka\Damm\Order\Order64::class,
                '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz+/',
                'aUDroBOmAJY85Vnk',
                'y',
            ],
            [
                \Sunaoka\Damm\Order\Order3::class,
                '210',
                '102',
                '0',
            ],
            [
                \Sunaoka\Damm\Order\Order4::class,
                '2301',
                '3201',
                '0',
            ],
            [
                \Sunaoka\Damm\Order\Order5::class,
                '21034',
                '31402',
                '4',
            ],
            [
                \Sunaoka\Damm\Order\Order7::class,
                '6325140',
                '5601432',
                '1',
            ],
            [
                \Sunaoka\Damm\Order\Order8::class,
                '15470632',
                '02713546',
                '7',
            ],
            [
                \Sunaoka\Damm\Order\Order9::class,
                '654738021',
                '706215384',
                '2',
            ],
            [
                \Sunaoka\Damm\Order\Order10::class,
                '5102638947',
                '1698274035',
                '8',
            ],
            [
                \Sunaoka\Damm\Order\Order11::class,
                'A0729648135',
                '03981456A27',
                '4',
            ],
            [
                \Sunaoka\Damm\Order\Order12::class,
                '317928A05B46',
                '6907B534A821',
                '2',
            ],
            [
                \Sunaoka\Damm\Order\Order13::class,
                'B3C614A890752',
                '913A7B864C250',
                'B',
            ],
            [
                \Sunaoka\Damm\Order\Order14::class,
                '704A28D5B13C96',
                '2568DB94307A1C',
                '7',
            ],
            [
                \Sunaoka\Damm\Order\Order15::class,
                'D749A826CB5103E',
                'B3C84571E96D2A0',
                '3',
            ],
            [
                \Sunaoka\Damm\Order\Order16::class,
                'B47D39C0A2EF8651',
                '6249AF108E7DB35C',
                '2',
            ],
            [
                \Sunaoka\Damm\Order\Order17::class,
                '3D8972C1EAB4G5F60',
                '2F64AE8DG739BC10',
                '9',
            ],
            [
                \Sunaoka\Damm\Order\Order18::class,
                'C0BHFD568A9273E1G4',
                'C179B5EDH32G0F64',
                'A',
            ],
            [
                \Sunaoka\Damm\Order\Order19::class,
                'HCEG052I98F314DB7A6',
                'CHBG9E475I31028D',
                '4',
            ],
            [
                \Sunaoka\Damm\Order\Order20::class,
                'BA6GD7FC0I253841H9EJ',
                'G91HC3DEBIF0A752',
                '9',
            ],
            [
                \Sunaoka\Damm\Order\Order21::class,
                '6JHF39I5G1KAEC820D47B',
                'DKAJ96B7CI8120G4',
                '4',
            ],
            [
                \Sunaoka\Damm\Order\Order22::class,
                'CDA2E14G98L0IF367JHB5K',
                'I04A28BE651FDHJ7',
                'L',
            ],
            [
                \Sunaoka\Damm\Order\Order23::class,
                '20EI67954AGMHCBK13JFLD8',
                '1HFD9JL8IEK47AB2',
                '3',
            ],
            [
                \Sunaoka\Damm\Order\Order24::class,
                '4M53JA1FLDI7NG8H0CE6B9K2',
                'E290ID1L5K8CBNHM',
                'K',
            ],
            [
                \Sunaoka\Damm\Order\Order25::class,
                '9AKCG5N40JHLO1826FMDE7I3B',
                '8GFJL5C21N670KOB',
                'F',
            ],
            [
                \Sunaoka\Damm\Order\Order26::class,
                '7MJ10H9OKAP8L6NCBDGF43IE52',
                'CAKE3I1HB7D9O6J5',
                'I',
            ],
            [
                \Sunaoka\Damm\Order\Order27::class,
                'K51FBL8GHQCI6DO23PANE0J7M94',
                'QINAG3OLKC19MD6H',
                'N',
            ],
            [
                \Sunaoka\Damm\Order\Order28::class,
                '6QEP0FM87IDA34HR92KCO1GBJ5LN',
                '58M3GEN74JO0DA6B',
                'J',
            ],
            [
                \Sunaoka\Damm\Order\Order29::class,
                '708B4MF26PQOEHRLJIG31DKN59SCA',
                '5LRIQ0AD4KM9H71B',
                'L',
            ],
            [
                \Sunaoka\Damm\Order\Order30::class,
                'N012OJR73SKPC5L8Q9TB4GFHEIDAM6',
                'O36T0AKJSGDIME87',
                'F',
            ],
            [
                \Sunaoka\Damm\Order\Order31::class,
                'ISJ51U73DAB42KQG9E6FCMH8LTNOPR0',
                '4L5EDMQ6TU8A0C2J',
                'M',
            ],
            [
                \Sunaoka\Damm\Order\Order32::class,
                'GDIN2HPKO60BUFTE8C1549JSRMAV3L7Q',
                '8L26DVJQ0NRUB1KC',
                'K',
            ],
            [
                \Sunaoka\Damm\Order\Order33::class,
                'N6HMKRWGFLB7VE2IJD9P14OA5CQT830SU',
                'JQ19F2DPL703K65U',
                'O',
            ],
            [
                \Sunaoka\Damm\Order\Order34::class,
                '3V1OQEX4LPUDRAJ0FMHB8N7T96I52CWGSK',
                'RTB5PC0OGM4WHQVK',
                'C',
            ],
            [
                \Sunaoka\Damm\Order\Order35::class,
                'YNRFB5A48SHV6MKX10Q2IG7WOUPJ39CTLDE',
                'XSBQRLA79MHY0IFE',
                'J',
            ],
            [
                \Sunaoka\Damm\Order\Order36::class,
                'QONAIE3ZH5SCYGL6TX90BD1PR47UVK82WFJM',
                'XEIYBMFVTO1QN3AG',
                '1',
            ],
            [
                \Sunaoka\Damm\Order\Order37::class,
                'QM6B4RaKS7T5C3XA0UZOP9Y2EI1NFDVL8HGJW',
                'L61KYJ4C9G0DQURI',
                'W',
            ],
            [
                \Sunaoka\Damm\Order\Order38::class,
                '43KS8NZaAWGCDJLEO1X569RYTUIVb0BP7FM2QH',
                'aKBb1IFJ7906SXYC',
                'S',
            ],
            [
                \Sunaoka\Damm\Order\Order39::class,
                'KDZ6EPIAb9HRVM02X7FUBLO5YSWCaNQcG3TJ814',
                'AU4CE83YFR75Z6LD',
                'E',
            ],
            [
                \Sunaoka\Damm\Order\Order40::class,
                '7MCS8W1T6YF4LKc5OQXI0VZGBPHUbdD39J2NRAaE',
                'F9ObJNc1U7KBCP5H',
                'I',
            ],
            [
                \Sunaoka\Damm\Order\Order41::class,
                'U3ZSV15KbeBM4FAREJa2c6NLXDI09GCWP8Hd7YTQO',
                'FU0417TeMRHPdaXA',
                'W',
            ],
            [
                \Sunaoka\Damm\Order\Order42::class,
                'RZLeMEJfUIKTGN9531VCPYSd6FbB7A8WHOc420aQXD',
                'JKbVFIe5dUXGEH97',
                'Y',
            ],
            [
                \Sunaoka\Damm\Order\Order43::class,
                'a2WIJVEZ6X8YBdSLPg9FDTCGecH1b7RKMQ3U40Of5AN',
                '8HOL3IENUQ72ACSG',
                '2',
            ],
            [
                \Sunaoka\Damm\Order\Order44::class,
                '71VFNU35D4EeR6fKZaOgQTW2PdXB9IcM0HCLY8ASGJhb',
                'JCGPT5E9FDHXSb6W',
                'Y',
            ],
            [
                \Sunaoka\Damm\Order\Order45::class,
                'JgGiFMTUeCN5Z7HO309YQfEKA64IB1Lh8VcWdXSDabPR2',
                'FLJ1Eh8SQgNG3Y25',
                '7',
            ],
            [
                \Sunaoka\Damm\Order\Order46::class,
                'VjhdbKJQW9eI6cX1NFTREfU0MOL5Y4GgSaHADi2ZPCB387',
                'icZPU0REAJ6LWKS3',
                'I',
            ],
            [
                \Sunaoka\Damm\Order\Order47::class,
                'ZIhciAN5RBak3OPeXSd1f78F2H49QV6G0MEgjJKbUYCLTDW',
                'XWACHbMiF5YhVPGQ',
                '4',
            ],
            [
                \Sunaoka\Damm\Order\Order48::class,
                'aKXjg61kNcAd08PMVIbGJQl4iZehDS95L2TFUOHBERfY7C3W',
                'B9Ti6FP2LH8MdCAX',
                'D',
            ],
            [
                \Sunaoka\Damm\Order\Order49::class,
                '9JUXDKYL5QW2mGk8FfjiTZCSaed6EhRglb1NB0cOA74HMPI3V',
                'feX9LgQHmbd40WAl',
                'F',
            ],
            [
                \Sunaoka\Damm\Order\Order50::class,
                'aMRkdlH1Ui3KGgCjnbXWP84OZceJB6EF9fhND0SVI7ALYQm2T5',
                'MkiIK4LNnl10B682',
                'K',
            ],
            [
                \Sunaoka\Damm\Order\Order51::class,
                'mZPOc4NQa9Y0RfVhn356S8glGDbdXj1CW7KioEkBeMFUAI2LHTJ',
                'RkWniQFlAa3o78XG',
                'W',
            ],
            [
                \Sunaoka\Damm\Order\Order52::class,
                'XGU0SkcL5WPCHnKjbZ4OAg7iB8D39lETehm61NIf2aMVYpJRoQFd',
                '2AQmVN3ZYn1RHcWj',
                '9',
            ],
            [
                \Sunaoka\Damm\Order\Order53::class,
                'OgTDbC6ihGXaNBP57V4RAopEKMIQ2ZL1FJf8YqdHkcSj9eWm3l0Un',
                'I4gRcfo6PeMWHTKp',
                'g',
            ],
            [
                \Sunaoka\Damm\Order\Order54::class,
                'clWDUoC62N3RfIQg7mkE5dGBbqFn0eMr948SAYhJaTijpVZO1XHLKP',
                'nrHAhLoCE0OZBdeR',
                'O',
            ],
            [
                \Sunaoka\Damm\Order\Order55::class,
                'Zop3sgSf4b5FrMqOH9Rl7TEjG08AhBQ2UL6niVXadC1JWYDkKcPNIme',
                'EOcRXSg2QrskdWhq',
                '8',
            ],
            [
                \Sunaoka\Damm\Order\Order56::class,
                'GKmI2fSEBVHbXNjMRhdnYgLkTD84qpWi3Q1e09JlP7tsFOrUZcCo65aA',
                '42CNVpFbBWT79cGq',
                'A',
            ],
            [
                \Sunaoka\Damm\Order\Order57::class,
                'qPOjNEI5WsuATdm714t2VQZhM0FCJ89XpRb36olLGKHBiDcafYSrkgeUn',
                'DsjlSMuIkEGJ5cKN',
                'F',
            ],
            [
                \Sunaoka\Damm\Order\Order58::class,
                's7G6hiPWrnVou8HJjML0IUNfp5dB4EmvbqgecZS931RYAQKCDFl2OatXkT',
                'nSBF6ei9N5KPhVga',
                'V',
            ],
            [
                \Sunaoka\Damm\Order\Order59::class,
                'cEO2Ti6a01XJRYeqPlHUn9mKQhB7Fjr8tASvsfILwgW5M3CdVZ4kobuGDNp',
                'UecwnZPk6jYH8oQS',
                'w',
            ],
            [
                \Sunaoka\Damm\Order\Order60::class,
                'Q5sKINZU8pnPFRMJYBaC14WwjXT7GtrhExA09kVSoHg36D2licOqeLfdmvbu',
                '1iPNmQsJFUxVXfg0',
                'v',
            ],
            [
                \Sunaoka\Damm\Order\Order61::class,
                'KaH6jrkJGDSMoVnNlyiIPh4CFqpbeOULZ2fR50md18XxvsAg73uctTWQBE9Yw',
                'bNciXG69Y0fOmWx8',
                'F',
            ],
            [
                \Sunaoka\Damm\Order\Order62::class,
                'LFvTjBY8XqRzr05JQ6WNmtuc4SbAZxCgOPoshK3yDU9fpd2Iln1iHGwVake7ME',
                'I9K6jbDgSoAXLrfc',
                'r',
            ],
            [
                \Sunaoka\Damm\Order\Order63::class,
                'kz8r4M6f2xRoP9GhVOiHptbUY5qJCDdK0BAInlZgEjwQvF1LNcWsX3e7TySau+m',
                'ldWTn1zJsybGq7AF',
                'R',
            ],
            [
                \Sunaoka\Damm\Order\Order64::class,
                '1b7eOYEXMCsx6JfAGDiS0ocgtwBa+d3p8WK5RzuTQIFk9l2UjHhN/rZynV4mvqPL',
                'aUDroBOmAJY85Vnk',
                'k',
            ],
        ];
    }
}
